---
title: "Multi-GPU Parallelism"
subtitle: "DiRAC GPU Performance Portability Workshop"
date: "2026-09-16"
date-format: "dddd DD MMMM YYYY"
from: markdown+emoji
format:
  clean-revealjs:
    embed-resources: false
    header-logo: media/dirac_logo.png
    footer: "DiRAC GPU Performance Portability Workshop"
    header: "https://tinyurl.com/dirac-multi-gpu"
    transition: slide
    sc-sb-title: true
    auto-play-media: true
    menu:
      openButton: false

filters:
 - reveal-header

authors:
 - name: Miren Radia
   role: Research Software Engineer
   affiliations:
     - name: University of Cambridge
 - name: Jamie Quinn
   role: Research Software Engineer
   affiliations:
     - name: DiRAC Training Team

---

# Introduction

## What we will cover

* [Very brief] recap of the Message Passing Interface (MPI)
* How to distribute work to GPUs using MPI
* GPU-aware MPI
* Optimization techniques to improve performance of multi-GPU applications

# MPI Recap

## What is MPI? {.smaller}

* The Message Passing Interface (MPI) is a *standard* for distributed memory
  parallel programming.
* It defines an application programming interface (API) to exchange messages
  between processes that don't [necessarily] share memory for C and Fortran:
  * Point to point communication e.g. `MPI_Send`, `MPI_Recv`
  * Collective communication e.g. `MPI_Bcast`, `MPI_Reduce`, `MPI_Alltoall`
* Third-party support for other languages e.g. Python (mpi4py) and Julia
  (MPI.jl)
* Version 5.0 of the standard was released on 5 June 2025 and defined ABI
  compatibility between MPI implementations allowing users to switch between
  implementations without recompiling their code[^1].
* Various different implementations e.g.:
  * Open MPI based: Open MPI, Nvidia HPC-X
  * MPICH based: MPICH, Intel MPI, Cray MPI, MVAPICH

[^1]: Currently only MPICH v5.0+ has support for this but older MPICH-based
implementations have had ABI compatibility between each other for a while.


## Example MPI program (C++)

```cpp
#include <mpi.h>
#include <iostream>

int main(int argc, char* argv[])
{
    MPI_Init(&argc, &argv);

    int world_size;
    MPI_Comm_size(MPI_COMM_WORLD, &world_size);

    int world_rank;
    MPI_Comm_rank(MPI_COMM_WORLD, &world_rank);

    std::cout << "Hello from rank " << world_rank << " of "
              << world_size << std::endl;

    MPI_Finalize();
}
```

## Example MPI program (Fortran)

```fortran
program hello_mpi
  use mpi_f08
  implicit none

  integer :: world_size, world_rank

  call MPI_Init()
  call MPI_Comm_size(MPI_COMM_WORLD, world_size)
  call MPI_Comm_rank(MPI_COMM_WORLD, world_rank)

  print *, "Hello from rank ", world_rank, " of ", world_size

  call MPI_Finalize()
end program hello_mpi
```

## MPI references

* [MPI Forum Documentation](https://www.mpi-forum.org/docs/)
* [Open MPI Documentation](https://docs.open-mpi.org)
* [MPICH Man Pages](https://www.mpich.org/static/docs/latest/)
* [Rookie HPC MPI Docs](https://rookiehpc.org/mpi/index.html)[^1]

[^1]: Some newer/more advanced MPI routines are missing here.

# Distributing work to GPUs

<!-- The inline SVG images are quite long hence included separately -->
{{< include includes/mapping-mpi-processes.qmd >}}

## Distributing GPUs to local MPI ranks (CUDA/HIP)

```cpp
int world_rank;
MPI_Comm_rank(MPI_COMM_WORLD, &world_rank);
MPI_Comm local_comm;
MPI_Comm_split_type(MPI_COMM_WORLD, MPI_COMM_TYPE_SHARED, world_rank,
                    MPI_INFO_NULL, &local_comm);

int local_rank = -1;
MPI_Comm_rank(local_comm, &local_rank);
MPI_Comm_free(&local_comm);

int num_devs = 0;
cudaGetDeviceCount(&num_devs);
cudaSetDevice(local_rank % num_devs);
```

## Distributing GPUs to local MPI ranks (OpenMP)

```fortran
use mpi_f08
use omp_lib

integer :: world_rank, local_rank, num_devs
type(MPI_Comm) :: local_comm

call MPI_Comm_rank(MPI_COMM_WORLD, world_rank)
call MPI_Comm_split_type(MPI_COMM_WORLD, MPI_COMM_TYPE_SHARED, world_rank, &
                         MPI_INFO_NULL, local_comm)

call MPI_Comm_rank(local_comm, local_rank)
call MPI_Comm_free(local_comm)

num_devs = omp_get_num_devices()
call omp_set_default_device(mod(local_rank, num_devs))
```

## Why one MPI process per GPU? {.smaller}

* Why not more GPUs per MPI process?
  * Each GPU has its own memory space and it makes sense to use MPI to
    communicate data between GPUs both intra-node and inter-node.
  * You would need to handle memory transfers between GPUs in the same MPI
    process manually (e.g. using CUDA/HIP or OpenMP) so would have two different
    methods of communicating data between GPUs.
* Why not more MPI processes per GPU?
  * This is possible if the work of a single MPI process is too small to fully
    utilize a whole GPU.
  * On Nvidia GPUs, to use multiple MPI processes per GPU efficiently, you need
    to use the Multi-Process Service (MPS) to reduce context switching
    overheads (check docs/HPC user support if system has MPS available).
  * On AMD GPUs, this is not necessary.
  * Best to start with one MPI process per GPU and only try more if necessary.
* Some GPUs (e.g. AMD MI250X and Intel Data Center GPU Max 1550/PVC) are
  essentially two GPUs fused together so it is often best here to use two MPI
  processes per GPU.

# GPU-aware MPI

## What is GPU-aware MPI? {.smaller}

* GPU-aware MPI implementations allow you to pass GPU pointers directly to MPI
  routines without having to copy data to host memory first.
* Often referred to as "CUDA-aware MPI" for Nvidia GPUs.
* Not part of the standard so implementation-dependent.
  * If available it is usually optional so you need to check if implementation
    has been built with it.
  * Should be available on all GPU HPC systems.
  * Best practice: keep copying data to host memory as a fallback.
* Open MPI is the most common implementation that can be built with GPU support
  for Nvidia or AMD GPUs (usually provided by the lower level UCX library).
  We will focus on it from now on.
* Consult system documentation for details: you may need to set environment
  variables to enable support:
  * `MPICH_GPU_SUPPORT_ENABLED=1` for MPICH and Cray MPI.
  * `I_MPI_OFFLOAD=1` for Intel MPI.
  * `MV2_USE_CUDA=1` or `MV2_USE_ROCM=1` for MVAPICH2.

## No GPU-aware MPI (CUDA/HIP) {auto-animate="true"}

Without GPU-aware MPI, data transfers between host and GPU memory must be
handled manually (or rely on managed/unified memory):

```{.cpp code-line-numbers="|5|12|"}
size_t size = 1024;
double* d_ptr;
double* h_ptr;
cudaMalloc(&d_ptr, size * sizeof(double));
cudaMallocHost(&h_ptr, size * sizeof(double));

<some CUDA kernel that fills d_ptr with data>

int dest_rank = 1;
int tag = 0

cudaMemcpy(h_ptr, d_ptr, size * sizeof(double), cudaMemcpyDeviceToHost);
MPI_Send(h_ptr, size, MPI_DOUBLE, dest_rank, tag, MPI_COMM_WORLD);
```

## With GPU-aware MPI (CUDA/HIP) {auto-animate="true"}

With CUDA/HIP, it's as simple as just passing a pointer to GPU memory to an MPI
routine:

```{.cpp code-line-numbers="|10"}
size_t size = 1024;
double* d_ptr;
cudaMalloc(&d_ptr, size * sizeof(double));

<some CUDA kernel that fills d_ptr with data>

int dest_rank = 1;
int tag = 0

MPI_Send(d_ptr, size, MPI_DOUBLE, dest_rank, tag, MPI_COMM_WORLD);
```

## Passing GPU pointers to MPI (OpenMP)

With OpenMP, it's necessary to add the following directive to ensure the GPU
pointer is passed:

```{.fortran code-line-numbers="|10,12"}
integer, parameter :: size = 1024
double precision, allocatable :: d_array(:)
integer :: dest_rank = 1, tag = 0

allocate(d_array(size))
!$omp target enter data map(alloc: d_array)

<some OpenMP kernel that fills d_array with data>

!$omp target data use_device_addr(d_array)
call MPI_Send(d_array, size, MPI_DOUBLE, dest_rank, tag, MPI_COMM_WORLD)
!$omp end target data
```

## How to build GPU-aware MPI programs {.smaller}

All examples below are for Open MPI but can use other MPI implementations by
suitably replacing `OMPI_*` environment variables.

<!-- Mention both CUDA/HIP and OpenMP  -->
* CUDA C++ (with `g++` as host compiler):
  ```{.bash code-line-numbers="false"}
  OMPI_CXX=nvcc mpicxx -x cu --ccbin=g++ --forward-unknown-to-host-compiler <nvcc and g++ flags> \
      -o my_mpi_cuda_program my_mpi_cuda_progam.cpp
  ```

* HIP C++: Set `OMPI_CXX=hipcc` or `OMPI_CXX=amdclang++` and then use `mpicxx`
  as the compiler e.g.:
  ```{.bash code-line-numbers="false"}
  OMPI_CXX=amdclang++ mpicxx -x hip --offload-arch=<gpu arch> -o my_mpi_hip_program my_mpi_hip_program.cpp
  ```

* Nvidia Fortran compiler with OpenMP:
  ```{.bash code-line-numbers="false"}
  OMPI_FC=nvfortran mpifort -mp=gpu -gpu=<gpu arch> -o my_mpi_openmp_program my_mpi_openmp_program.f90
  ```

* AMD Flang compiler with OpenMP:
  ```{.bash code-line-numbers="false"}
  OMPI_FC=amdflang mpifort -fopenmp  -fopenmp-targets=<gpu arch> -o my_mpi_openmp_program my_mpi_openmp_program.f90
  ```

## What's happening under the hood? {.smaller}

* Simple and naive GPU-aware implementation (or fallback):
  * MPI implementation detects GPU pointer and copies data to host memory before
    sending it over the network.
  * On the receiving side, data is copied from host memory to GPU memory.
* Most GPU-aware MPI implementations use a more efficient approach that allows
  data to be sent directly between GPU memory without going through the host:
  * For GPUs on the same node, this can be done using peer-to-peer (P2P) memory
    access.
  * For GPUs on different nodes, this can done using remote direct memory access
    (RDMA) over the network.
* Nvidia: GPUDirect P2P and GPUDirect RDMA (GDR)
* AMD: RDMA and P2P are part of the AMD kernel driver.

## No GPU-aware MPI

Without GPU-aware MPI, data must be copied to host memory. There is also some
additional overhead in copying data to/from pinned memory.

{{< include includes/communication-no-gpu-aware-mpi.qmd >}}

## GPU-aware MPI without P2P/RDMA

Even without P2P/RDMA, GPU-aware MPI is still more efficient than non-GPU-aware
MPI as the MPI library can use lower-level optimizations to copy data between
GPU and host memory.

{{< include includes/communication-gpu-aware-no-p2p-rdma.qmd >}}

## GPU-aware MPI with P2P/RDMA

GPU-aware MPI with P2P/RDMA is the most efficient as it allows data to be sent
directly between GPU memory without going through host memory.

{{< include includes/communication-gpu-aware-p2p-rdma.qmd >}}

## Example: Jacobi solver

## Example: Domain decomposition

## Exercise: Jacobi solver

## Exercise: Solution

# Optimization techniques

## Why optimization is *more* important on GPUs

## Recap: Node architecture and system topology

## NUMA, affinity and GPU distribution

## Example GPU binding script

## Exercise: Binding scripts

## Packing kernels

<!-- Remove MPI derived datatypes -->
<!-- Mention asynchronous kernels -->

## Non-blocking MPI communication

## Collective operations

## Exercise: Packing kernels and non-blocking communication

## Exercise Solution

## Overlapping communication and computation

## Exercise: Overlapping communication and computation

## Exercise: Solution

# Conclusion

## Summary

## Additional resources and references
